#!/usr/bin/env python

# ensure that we're setting up a container with enough memory
# Check user's docker settings to see if 8 Gb of memory
# are allocated to containers.
# Otherwise, issues can ensue especially when pip installing
# large packages like torch

import os
import json
import sys
RED = '\033[91m'

if __name__ == '__main__':
    path = os.path.expanduser('~/Library/Group Containers/group.com.docker/settings.json')
    with open(path, 'r') as settings_file:
        settings_string = settings_file.read()
    settings_dict = json.loads(settings_string)
    memory_allocation = settings_dict['memoryMiB']
    if memory_allocation < 8192:
        print(RED, """ML Eng recommends allocating at least 8Gb of memory to containers
            To change this setting, please update your docker settings
            and restart docker, as outlined in the Confluence page linked below,
            and then rerun this script
            https://confluence.mailchimp.com/pages/viewpage.action?pageId=259195390
            """)
        sys.exit(1)
