#!/usr/bin/env bash
#
# This will stop all containers defined in docker-compose files.

cp Dockerfile Dockerfile.tmp
docker-compose -f docker-compose.yml -f docker-compose.dev.yml down -v --remove-orphans
